#
# GNU Makefile for "dma_demo" demonstration program (Linux)
#
# (C) Copyright 2018 Alpha Data
#
# Available targets:
# ------------------
#
#   all           - Builds executable
#   clean         - Removes executable and object files
#
# MAKE variables or environment variables recognized by this Makefile:
#
#   BIARCH        - If value is yes, builds for bi-archtecture 64-bit system
#                   (i.e. both 32-bit and 64-bit binaries are created).
#   SYSROOT       - If specified, is the root of the target filesystem;
#                   typically used when cross-building.
#   CROSS_COMPILE - Prefix before tools, e.g. arm-linux-; typically used when
#                   cross-building. If cross-building, the target platform'script
#                   toolchain must be in the PATH.
#

NAME=run_dpu_test
SDK_LOCATION=/home/am/local_vivado_projects/test_sdks/admpcie9v3_sdk-1.2.0


include version.mak
include template.mak
